# BBPP job-1 / Knots Legacy V29.3.0.20260920
# Dimitri: DATUM and BIP-110 keys match V3. Copy-paste safe for those rows.
# job: home-validator
# Stay on SHA-256 primary line.

listen=1
server=1

prune=550
txindex=0
blockfilterindex=0
coinstatsindex=0
disablewallet=1

datacarrier=1
datacarriersize=0

acceptnonstddatacarrier=0
acceptnonstdtxn=0

permitbaremultisig=0
permitbarepubkey=0

rejectparasites=1
rejecttokens=1

antispamscriptpubkeysize=1
antispampushdatasize=1
antispamwitnessversion=1
antispamtaprootannex=1
antispamcontrolblocksize=1
antispamopsuccess=1
antispamtapscriptif=1

mempoolreplacement=fee,-optin

maxmempool=300
persistmempool=1
mempoolexpiry=336

rpcallowip=127.0.0.1
rpcbind=127.0.0.1

datum=0

# corepolicy=1
# datacarriersize=83
# datacarriersize=100000
# datum=1
